### ISSUE TITLE
Tab-bar do APP

### ISSUE THREAD

**Issue by MarceloDanigno** [MarceloDanigno/ProjetoPDSII#17]

**Comment by MarceloDanigno** [comment]
Barra horizontal no topo da página que contém botões (icones) para login(direita), registro(direita), home (logo ainda não definido, usar qualquer coisa; esquerda) e no centro duas barrinhas para All e Following (dois botões normais que não fazem nada por enquanto).

**Comment by MarceloDanigno** [comment]
Também revisar redirecionamento dos botões

**Comment by Brongar** [comment]
feito!
O logo é um botão para homepage.
